# Generated by Django 2.2 on 2020-05-04 08:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField()),
                ('saldo_inicio', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('titular', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('importe', models.DecimalField(decimal_places=2, error_messages={'valor negativo': 'Sólo son admisibles transferencias superiores a 0.01 €'}, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0, 1)])),
                ('concepto', models.CharField(max_length=90)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario', to=settings.AUTH_USER_MODEL)),
                ('cuenta_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_beneficiario', to='cuentas.Cuenta')),
                ('cuenta_ordenante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_ordenante', to='cuentas.Cuenta')),
                ('ordenante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
