# Generated by Django 2.2 on 2020-04-20 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField()),
                ('saldo_inicio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('titular', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=20)),
                ('concepto', models.CharField(max_length=90)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario', to=settings.AUTH_USER_MODEL)),
                ('cuenta_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_beneficiario', to='cuentas.Cuenta')),
                ('cuenta_ordenante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_ordenante', to='cuentas.Cuenta')),
                ('ordenante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
